namespace:
  create: false
  name: kubeflow

pvc:
  name: recsys-mlops-pvc
  storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

secret:
  name: recsys-mlops-runtime
  minioEndpoint: http://minio.experiment-tracking.svc.cluster.local:9000
  minioRootUser: minio
  minioRootPassword: minio123
  mlflowTrackingUri: http://mlflow.experiment-tracking.svc.cluster.local:5000
  mlflowExperimentName: recsys-bst-ranking
  modelRegistryPostgresUri: postgresql://mlflow:mlflow123@postgres.experiment-tracking.svc.cluster.local:5432/mlflow
  modelStoreBucket: recsys-model-store
  modelStorePrefix: triton/bst
  promotionManifestKey: promotions/bst/latest.json

rbac:
  create: true
  serviceAccountNames:
    - default
    - pipeline-runner
    - default-editor
