namespace:
  create: false

staticVolumes:
  enabled: false

registry:
  pvc:
    volumeName: ""
    storage: 10Gi
    storageClassName: standard-rwo

jenkins:
  imagePushRegistry: asia-southeast1-docker.pkg.dev/rec-sys-503309/recsys
  imagePullRegistry: asia-southeast1-docker.pkg.dev/rec-sys-503309/recsys
  requireGcpArtifactRegistry: true
  runtimeCredentialsSecret:
    enabled: true
  dind:
    useJenkinsHomePvc: true
  runtimeTools:
    installOnStartup: true
  webhookIngress:
    enabled: true
  pvc:
    volumeName: ""
    storage: 50Gi
    storageClassName: standard-rwo

modelRolloutWatcher:
  enabled: true
  image: asia-southeast1-docker.pkg.dev/rec-sys-503309/recsys/recsys-mlops-training:gcp
  imagePullPolicy: Always
  autoProgressiveEnabled: true
  progressiveWeights: "10,25,50"
