namespace:
  create: true
  name: ci

serviceMesh:
  jenkinsPodAnnotations:
    sidecar.istio.io/inject: "false"

staticVolumes:
  enabled: true
  reclaimPolicy: Retain
  jenkinsHostPath: /data/recsys-ci/jenkins-home
  registryHostPath: /data/recsys-ci/registry-data

registry:
  enabled: true
  image: registry:3.0.0
  replicas: 1
  service:
    name: recsys-registry
    type: ClusterIP
    port: 5000
  pvc:
    name: recsys-registry-data
    volumeName: recsys-ci-registry-data
    storage: 30Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: recsys-ci-local
  nodeProxy:
    enabled: true
    image: registry.k8s.io/minikube/kube-registry-proxy:v0.0.11
    hostPort: 5001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 1Gi

jenkins:
  enabled: true
  image: jenkins/jenkins:lts-jdk17
  replicas: 1
  adminUser: admin
  adminSecretName: recsys-jenkins-admin
  github:
    projectUrl: https://github.com/itsmekhoathekid/RecSys-MLops/
    repositoryUrl: https://github.com/itsmekhoathekid/RecSys-MLops.git
    branchSpec: "*/main"
  plugins:
    installOnStartup: true
    required:
      - workflow-aggregator
      - workflow-job
      - workflow-cps
      - workflow-scm-step
      - workflow-multibranch
      - pipeline-stage-view
      - junit
      - git
      - github
  runtimeTools:
    installOnStartup: false
    kubectlVersion: v1.33.0
    helmVersion: v3.18.4
  seedJob:
    enabled: true
    name: RecSys-GitHub-CICD
    scriptPath: Jenkinsfile
  service:
    name: recsys-jenkins
    type: ClusterIP
    httpPort: 8080
    agentPort: 50000
  webhookIngress:
    enabled: false
    className: nginx
    host: ""
    path: /github-webhook/
    pathType: Prefix
    annotations: {}
  pvc:
    name: recsys-jenkins-home
    volumeName: recsys-ci-jenkins-home
    storage: 20Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: recsys-ci-local
  imagePushRegistry: recsys-registry.ci.svc.cluster.local:5000/recsys
  imagePullRegistry: localhost:5001/recsys
  requireGcpArtifactRegistry: false
  javaOpts: "-Djenkins.install.runSetupWizard=false -Dhudson.model.DownloadService.never=true"
  dind:
    enabled: true
    image: docker:28-dind
    storageDriver: overlay2
    useJenkinsHomePvc: false
    pvc:
      enabled: false
      name: recsys-jenkins-docker-graph
      storage: 80Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: ""
    insecureRegistries:
      - recsys-registry.ci.svc.cluster.local:5000
      - localhost:5001
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: "2"
        memory: 3Gi
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: "1"
      memory: 2Gi

rbac:
  create: true
  serviceAccountName: recsys-jenkins
  clusterWide: true
