apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  MINIO_ENDPOINT: {{ .Values.secret.minioEndpoint | quote }}
  MINIO_ROOT_USER: {{ .Values.secret.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secret.minioRootPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.minioRootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.minioRootPassword | quote }}
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.secret.minioEndpoint | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.secret.mlflowTrackingUri | quote }}
  MLFLOW_EXPERIMENT_NAME: {{ .Values.secret.mlflowExperimentName | quote }}
  MODEL_REGISTRY_POSTGRES_URI: {{ .Values.secret.modelRegistryPostgresUri | quote }}
