storageClassName: standard-rwo

kafka:
  retentionHours: "24"
  segmentBytes: "268435456"
  retentionCheckIntervalMs: "60000"
  persistence:
    enabled: true
    storage: 60Gi

zookeeper:
  persistence:
    enabled: true
    storage: 5Gi
