{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: {{ .Values.name }}, namespace: {{ .Values.namespace }} }
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: {{ .Values.name }}}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: {{ .Values.namespace }}}
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: {{ .Values.networkPolicy.observabilityNamespaceLabel }}}
      ports: [{protocol: TCP, port: {{ .Values.service.targetPort }}}]
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: kube-system}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: {{ .Values.networkPolicy.apiServingNamespaceLabel }}}
      ports: [{protocol: TCP, port: 80}]
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: {{ .Values.networkPolicy.observabilityNamespaceLabel }}}
      ports:
        - {protocol: TCP, port: 4317}
        - {protocol: TCP, port: 9090}
{{- end }}
