apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recsys-feature-rag-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: false
