apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.mountPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath | quote }}
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.serviceAccount.name }}
            namespace: {{ .Values.vault.auth.serviceAccount.namespace }}
