apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recsys-kagent-agent.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      recsys.ai/autoscale-target: {{ .Values.agent.name }}
