kserve:
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
      nvidia.com/gpu: "1"
    limits:
      cpu: "3"
      memory: 8Gi
      nvidia.com/gpu: "1"
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-t4
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  sharedMemory:
    sizeLimit: 1Gi

api:
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

autoscaling:
  http:
    api:
      minReplicas: 2
      maxReplicas: 6
      requestRate:
        targetValue: 10
        window: 30s
        granularity: 1s
  kserveResource:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    pollingInterval: 15
    cooldownPeriod: 240
    cpu:
      enabled: true
      metricType: Utilization
      value: "60"
