kserve:
  enabled: true
  namespace:
    create: true
    name: kserve-triton-inference
  servingRuntime:
    create: true
    name: kserve-tritonserver
    image: nvcr.io/nvidia/tritonserver:23.05-py3
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
  inferenceService:
    name: recsys-bst-triton
    deploymentMode: RawDeployment
    storageUri: s3://recsys-model-store/triton/bst/latest
  serviceAccount:
    name: recsys-kserve-minio
  secret:
    name: recsys-kserve-minio
    minioEndpoint: minio.experiment-tracking.svc.cluster.local:9000
    minioUseHttps: "0"
    minioRegion: us-east-1
    accessKeyId: minio
    secretAccessKey: minio123
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

api:
  namespace:
    create: true
    name: api-serving
  name: recsys-api-serving
  image: recsys-api-serving:local
  imagePullPolicy: IfNotPresent
  replicas: 2
  rollout:
    maxSurge: 1
    maxUnavailable: 0
    minReadySeconds: 10
    progressDeadlineSeconds: 120
  service:
    port: 80
    targetPort: 8080
  config:
    tritonUrl: recsys-bst-triton-predictor.kserve-triton-inference.svc.cluster.local:9000
    tritonModelName: bst_ensemble
    redisHost: redis.recsys-dataflow.svc.cluster.local
    redisPort: "6379"
    defaultTopK: "10"
    modelVersion: latest
    forceNotReady: "0"
    allowFeatureFallback: "0"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

autoscaling:
  http:
    enabled: true
    externalScalerAddress: keda-add-ons-http-external-scaler.keda:9090
    api:
      enabled: true
      name: recsys-api-serving-http
      host: recsys-api-serving.local
      pathPrefix: /
      minReplicas: 1
      maxReplicas: 5
      scaledownPeriod: 120
      requestRate:
        targetValue: 5
        window: 30s
        granularity: 1s
    kserve:
      enabled: false
      name: recsys-bst-triton-http
      host: recsys-bst-triton.local
      deploymentName: recsys-bst-triton-predictor
      serviceName: recsys-bst-triton-http
      targetServiceSelector:
        app: isvc.recsys-bst-triton-predictor
      pathPrefix: /
      minReplicas: 1
      maxReplicas: 3
      scaledownPeriod: 180
      requestRate:
        targetValue: 3
        window: 30s
        granularity: 1s
    limits:
      cpu: 500m
      memory: 512Mi
  kserveResource:
    enabled: true
    name: recsys-bst-triton-resource
    deploymentName: recsys-bst-triton-predictor
    minReplicas: 1
    maxReplicas: 3
    pollingInterval: 15
    cooldownPeriod: 180
    restoreToOriginalReplicaCount: true
    hpaName: recsys-bst-triton-predictor
    cpu:
      enabled: true
      metricType: Utilization
      value: "50"
    memory:
      enabled: false
      metricType: Utilization
      value: "70"
