kserve:
  resources:
    requests:
      cpu: "400m"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  servingRuntime:
    resources:
      requests:
        cpu: "400m"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi
  sharedMemory:
    sizeLimit: 512Mi

api:
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

featureApi:
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

autoscaling:
  http:
    api:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      requestRate:
        targetValue: 10
        window: 30s
        granularity: 1s
  prometheus:
    enabled: true
    api:
      minReplicas: 1
      maxReplicas: 3
      requestRate:
        targetValue: "4"
        activationThreshold: "1"
        window: 1m
      latency:
        targetValue: "0.15"
        activationThreshold: "0.04"
        window: 1m
    featureApi:
      minReplicas: 1
      maxReplicas: 3
      requestRate:
        targetValue: "4"
        activationThreshold: "1"
        window: 1m
      latency:
        targetValue: "0.08"
        activationThreshold: "0.03"
        window: 1m
  kserveResource:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    pollingInterval: 15
    cooldownPeriod: 240
    cpu:
      enabled: true
      metricType: Utilization
      value: "35"
