controller:
  replicas: 1
  pdb:
    enabled: false
  topologySpreadConstraints: []
  nodeSelector:
    cloud.google.com/gke-nodepool: recsys-mlops-cpu
substrateWorkerPool:
  replicas: 1
  template:
    nodeSelector:
      cloud.google.com/gke-nodepool: recsys-mlops-cpu
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi
