FROM asia-southeast1-docker.pkg.dev/recsys-mlops-506406/recsys/recsys-airflow@sha256:ad88d23e2a8a83f052016d7ba6591282ecb61dd2ca644e445210489c28f121f7
COPY --chown=airflow:root recsys_rag_item_index.py /opt/recsys/apps/data-platform/src/orchestration/airflow/dags/recsys_rag_item_index.py
