apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workload-pvc
  namespace: llm-inference
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
