apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.api.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.api.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.api.name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
