{{- if .Values.featureApi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.featureApi.name }}-registry
  namespace: {{ .Values.api.namespace.name }}
type: Opaque
stringData:
  FEAST_POSTGRES_USER: {{ default "feast" .Values.featureApi.config.feastPostgresUser | quote }}
  FEAST_POSTGRES_PASSWORD: {{ default "feast" .Values.featureApi.config.feastPostgresPassword | quote }}
{{- end }}
