{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: recsys-data-platform-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DATA_PLATFORM_MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  DATA_PLATFORM_MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
  POSTGRES_USER: {{ .Values.sourcePostgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.sourcePostgres.password | quote }}
  AIRFLOW_POSTGRES_USER: {{ .Values.airflowPostgres.user | quote }}
  AIRFLOW_POSTGRES_PASSWORD: {{ .Values.airflowPostgres.password | quote }}
{{- end }}
