name: recsys_warehouse
version: "1.0.0"
config-version: 2
profile: recsys_warehouse

model-paths: ["models"]
test-paths: ["tests"]

models:
  recsys_warehouse:
    production:
      +schema: production
      +materialized: table

