substitutions:
  _IMAGE_REPO: asia-southeast1-docker.pkg.dev/rec-sys-503309/recsys
  _TAG: gcp
  _BASE_TAG: gcp

options:
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY

timeout: 2400s

steps:
  - id: data-ingestion
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - RECSYS_BASE_IMAGE=${_IMAGE_REPO}/recsys-base-python:${_BASE_TAG}
      - -f
      - apps/data-platform/Dockerfile.data-ingestion
      - -t
      - ${_IMAGE_REPO}/recsys-data-ingestion:${_TAG}
      - .

  - id: feature-store
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - RECSYS_BASE_IMAGE=${_IMAGE_REPO}/recsys-base-python:${_BASE_TAG}
      - -f
      - apps/data-platform/Dockerfile.feature-store
      - -t
      - ${_IMAGE_REPO}/recsys-feature-store:${_TAG}
      - .

  - id: drift-retrain
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - RECSYS_BASE_IMAGE=${_IMAGE_REPO}/recsys-base-python:${_BASE_TAG}
      - -f
      - apps/data-platform/Dockerfile.drift-retrain
      - -t
      - ${_IMAGE_REPO}/recsys-drift-retrain:${_TAG}
      - .

images:
  - ${_IMAGE_REPO}/recsys-data-ingestion:${_TAG}
  - ${_IMAGE_REPO}/recsys-feature-store:${_TAG}
  - ${_IMAGE_REPO}/recsys-drift-retrain:${_TAG}
